version: '3'
services:
  nodejsjchurivanti:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejsjchurivanti
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "12200:12299"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-networkjchurivanti
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  db:
    image: mongo:4.1.8-xenial
    container_name: dbjchurivanti
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdatajchurivanti:/data/db
    networks:
      - app-networkjchurivanti

networks:
  app-networkjchurivanti:
    driver: bridge

volumes:
  dbdatajchurivanti:
  node_modules: